nextcloud/gallery

controller/configapicontroller.php, controller/configcontroller.php, controller/filesapicontroller.php, controller/filescontroller.php, controller/httperror.php, js/galleryview.js, tests/unit/GalleryUnitTest.php, tests/unit/controller/ConfigControllerTest.php, tests/unit/controller/FilesControllerTest.php, tests/unit/controller/HttpErrorTest.php
Backport of https://github.com/nextcloud/gallery/pull/154
No backport to older versions required.
cc @MorrisJobke @oparoz Please review.
=> [stable10] Do not display technical error messages

js/galleryview.js
Otherwise somebody could let somebody open "http://10.211.55.7/stable9/index.php/apps/gallery/#Please contact support@foo.com%00" and thus make the person believe that this is part of a valid error message. As an hardening measure, we should not display anything rather in this case.
@oparoz Thoughts? I'd appreciate a review and backport if you don't consider this too ugly :-)
=> Do set albumpath to an empty value if an error is thrown

templates/authenticate.php, templates/part.content.php, templates/part.filenotfounderror.php, templates/part.internalservererror.php, templates/part.linkerror.php, templates/public.php
See https://github.com/nextcloud/server/pull/1948
cc @oparoz
=> Move away from legacy OC_L10N

appinfo/app.php
Ref https://github.com/nextcloud/server/pull/2448
Licence: AGPL
@oparoz
=> Only load scripts on the files and sharing pages

appinfo/application.php, preview/preview.php, service/previewservice.php, tests/unit/preview/PreviewTest.php, tests/unit/service/PreviewServiceTest.php
* Rip out private calls to \OC\Preview
* Use \OCP\IPreview so we use the shared previews by default
* Leave the wrapper for now
Fixes: https://github.com/nextcloud/gallery/issues/185
TODO:
=> Make use of the IPreview so we use shared previews

css/styles.css
See https://github.com/nextcloud/server/pull/1657
=> Clean all superposed white backgrounds

css/upload.css, js/galleryview.js, js/vendor/owncloud/newfilemenu.js
Refs: nextcloud/server#3118
Ps: non related to this pr, but the other icons are still using img. It could be great if you could use span with icon inside instead (see buttons in files for example)
=> Popover to css guidelines

js/slideshow.js
Fixes: #160
Hide icon-loading-dark after loading the image and displaying it back when the image is loading.
@oparoz
=> Hide icon-loading-dark after loading the image

templates/public.php
Revert of 2056db39406a5a0348eb76b60eb6ae1ede69d7a6 because we fixed it in core.
=> There is no more enterprise and refix the footer

css/gallerybutton.css, js/galleryview.js, templates/part.content.php
Please review @oparoz @MariusBluem @MorrisJobke 
This is the equivalent of https://github.com/nextcloud/server/pull/4337 for the Gallery, simply renaming »share-button« to share_d_-button so that Adblock doesn’t hide it and mess it up.
=> Fix Gallery share button not showing with Adblock

templates/public.php
This fixes a problem due to `vendor/nextcloud/share.js` missing from generated pages.
Fixes: #270
Licence: MIT
@oparoz 
@icewind1991
=> Merge JS for public pages

lib/Environment/Environment.php
fixes errors like this:
```
"url":"/apps/gallery/preview/426429?width=3400&height=3400&c=594c37c83d999&requesttoken=VY8nKK5eeu3W6uVKtFvD+YSnXVfoXdas+mQvmFgXZGU=:YsZFTOgXCoOk3td/wQiVivTKFTOpC5fKmSNswDRQNFE=",
"message":"Undefined offset: 0 at /var/www/nextcloud/apps/gallery/lib/Environment/Environment.php#360",
```
and 
```
"url":"/apps/gallery/preview/426429?width=3400&height=3400&c=594c37c83d999&requesttoken=VY8nKK5eeu3W6uVKtFvD+YSnXVfoXdas+mQvmFgXZGU=:YsZFTOgXCoOk3td/wQiVivTKFTOpC5fKmSNswDRQNFE=",
"message":"ExceptionCould not locate node linked to ID: 426429",
```
to only log the last error and not both.
=> Fix logged error if file ID is not available

templates/public.php
Fixes: #269 
Also check https://github.com/nextcloud/server/pull/5920
By the way, since this might be backported, logo fix only affects bug introduced in Nextcloud v13, but backporting this PR will not introduce a regression.
Before:
After:
=> Fix download icon and logo on gallery share view

css/gallerybutton.css, js/gallery.js, js/gallerybutton.js, js/galleryview.js, templates/part.content.php, templates/public.php
Fixes wrong styling in files app and gallery due to new button styles in server nextcloud/server#3187
=> Remove obsolete/faulty css for the top right button

README.md
Assets pipelining has been removed since nextcloud 10: https://docs.nextcloud.com/server/10/admin_manual/configuration_server/js_css_asset_management_configuration.html
=> README: remove assets pipelining instructions

js/vendor/nextcloud/share.js
This was interfering with some other menus on the nextcloud server
@nextcloud/javascript @nextcloud/designers
=> Fixed too wide selector for the popovermenu

lib/Service/FilesService.php
Fixes: When e.g. a share folder is not available OCP\StorageNotAvailableException is throw, but was never catched. Rendering Gallery broken for everything.
Needs backporting to 12 at least (didn't test 11).
Licence:  AGPL
=> Ignore unavailable storage instead of breaking for all

.travis.yml, composer.json
Fixes: #329
Licence: AGPL
Make acceptance tests run and pass on Travis by updating the whole toolchain.
* Add missing dbus-x11 package needed for Firefox to run (package has been removed in recent Travis images by default)
* Update selenium to v3, alongside with geckodriver (only available interface between Webdriver and Firefox in recent Firefox versions)
* Add access_log in case of failure, quite useful in a lot of cases
* Update Codeception to 2.3 (it appears that it is not related at all to our issue but after testing it does not seem to do any harm)
* Travis has problems with intermitent failures with acceptance tests regarding login (which is still better than no test at all but far from ideal) that seem impossible to reproduce with local phantomjs.
=> Make acceptance tests run and pass on Travis

.travis.yml
dbus fails to install, removing it does not cause havok probably because of new version of Firefox used in previous PR #330.
Fixes: #329 (again)
=> Travis: remove dbus which seems no longer needed.

css/public.css
in shared link view the gallery is not scrollable in ie11
=> height fix for IE11

lib/Service/FilesService.php
This fixes an endless recursion for the case, that an external storage is mounted to "/". Then the `isRootFolder` method never evaluated to true, because a trailing slash was the actual diff between the current path and the root folders path.
@icewind1991 @oparoz Is this okay to be handled here or should we fix it in the server filesystem handling?
=> Fix the root folder detection for mounts points to '/'

lib/Service/FilesService.php
This fixes an endless recursion for the case, that an external storage is mounted to "/". Then the `isRootFolder` method never evaluated to true, because a trailing slash was the actual diff between the current path and the root folders path.
Backport of #339
=> [stable12] Fix the root folder detection for mounts points to '/'

css/slideshow.css
Was overwritten by attributes that where applied directly on the dom node.
Fixes https://github.com/nextcloud/server/issues/7486
=> Fix chess board background for transparent images in slide show

css/gallerybutton.css, css/public.css, css/styles.css, css/upload.css, js/gallerybutton.js, templates/part.content.php, templates/public.php
Fixes nextcloud/server#7374
Needs nextcloud/server#7478
=> Fixed gallery button insertion script and design fix

css/share.css, js/gallery.js, js/slideshowcontrols.js
Fixes #345
Although #345 refers to the share dropdown in the slideshow the issue happened too in the share dropdown for folders in the gallery; this pull request fixes both.
=> Fix three dots menu visible in share dropdown

js/slideshow.js
Although this will be obsoleted when #276 is fixed until then the _Delete_ and _Download_ buttons had a tooltip, but the other buttons did not*, which was inconsistent. Now a tooltip was added for the _Close_, _Play_ and _Pause_ buttons.
*The _Share_ button already has a tooltip or not depending on whether #356 was merged or not when you read this :-)
Note, however, that tooltips where not added to the _Previous_ and _Next_ buttons as due to their extremely large area the tooltips appear too frequently and are more "noisy" than useful.
#355 is needed to prevent the tooltip for the _Pause_ icon to be hidden when the progress increases.
@nextcloud/designers
=> Add missing tooltips to slideshow buttons

css/slideshow.css
The progress filling for the pause icon is a next sibling of the pause icon in the DOM. Both had the same z-index, so the progress filling element appeared in front of the pause icon. Due to this, if the pointer was hovering on the pause icon the hovered element could change from the pause icon to the progress filling when its height was increased, which in turn caused the highlight of the pause icon to disappear even if the pointer was not moved. Now the z-index of the progress filling was reduced to be shown behind the pause icon instead, which ensures that the pause icon is always the one being hovered.
Before:
After:
Even if the progress is now shown behind the pause icon as both [the pause icon](https://github.com/nextcloud/gallery/blob/38d5fb6ffb4d7c06662713bd2a8858c6f8c1860b/css/sli …
=> Put progress filling behind pause icon

css/slideshow.css
Fixes #313 
The jQuery UI Datepicker Widget automatically [sets the `z-index` of the date picker element to the `z-index+1` of the element it is called on](https://github.com/jquery/jquery-ui/blob/1.10.0/ui/jquery.ui.datepicker.js#L747). However [the server sets the `z-index` of the date picker using `!important` in its CSS files](https://github.com/nextcloud/server/blob/5591ea6e8bef0f87d1ebc915fd43a9acd7719890/core/css/share.scss#L204), so it overrides the value set directly on the element. As the `z-index` of the slideshow is `100000`, the `z-index` of the date picker element set in the server is `1111`, and the date picker element is a sibling of the slideshow element the date picker appears behind it and thus it is not visible.
But, why is the `z-index` explicitly set in the server …
=> Fix date picker not visible in slideshow sharing dialog

css/slideshow.css
=> [stable12] Fix date picker not visible in slideshow sharing dialog

css/slideshow.css, js/slideshow.js, js/slideshowcontrols.js, templates/slideshow.php
The share button is now an input element like the rest of the slideshow buttons.
Besides getting a cleaner code it fixes the share button not being hidden like the rest of the slideshow buttons when the pointer was not moved for three seconds.
This pull request also cleans some related code and adds a tooltip for the _Share_ button.
In the _stable12_ branch the _Share_ button was hidden, but there was a small glitch: while the rest of the buttons fade from their current opacity (0.5) the _Share_ button first changed to an opacity of 1 and then faded, which made the _Share_ button look like it was highlighted.
If this is worth a backport tell me ;-)
@nextcloud/designers
=> Unify slideshow share button with the rest of slideshow buttons

js/slideshowcontrols.js
Fixes (in master) #272
Fixes (in master) #321
When in slideshow mode certain keys trigger actions like toggling full screen or zooming. However, due to event bubbling, those actions were triggered too when typing in the input fields of the share dropdown. Instead of stopping the propagation in each input field this is now fixed by not triggering the actions if the element that received the key press was an input field.
=> Fix shortcuts activated when typing in the share dropdown

js/vendor/nextcloud/share.js
Fixes (in master) #300 
`_addShareWith` adds a share to the `#shareWithList` element, which is a descendant of the share dropdown. However, the _Sharing_ tab of the Files app sidebar contains its own `#shareWithList` element, so when the share dropdown is shown on top of the Files app (by clicking on an image
and then sharing it from the slideshow) and the _Sharing_ tab is open in the sidebar the share element ends added to the wrong element. To prevent this the matched element is now limited to descendants of the share dropdown.
Note, however, that there should not be two elements with the same ID in the same page. A better solution would have been to ensure that, but as [the sharing code seems to be going to be eventually removed from the gallery and replaced with a sidebar component …
=> Fix adding shares to wrong HTML element

css/share.css, js/vendor/nextcloud/share.js
When searching or selecting a sharee in the _shareWith_ field a loading icon is shown. However, as the icon had a relative position and the _shareWith_ field uses the full width of the share dropdown the icon was shown in a new line below the field. Moreover, due to its `right` CSS property the icon was also shown outside the dropdown itself. Now, during the search for or the selection of a sharee, the loading icon replaces the information icon shown in the _shareWith_ field, just like done in the sharing section of the server.
Before (the icon is hardly visible, I should have used another background, I know :-) ):
After:
This should be backported to Nextcloud 13. It also happens in Nextcloud 12... worth a backport there?
@nextcloud/designers
=> Fix loading icon position in "shareWith" field

.travis.yml
Fixes #337 
[The server uses the Imagick PHP extension to generate PostScript previews](https://github.com/nextcloud/server/blob/3d4c698f448925aca62976175ffd4bab9694c7d6/lib/private/PreviewManager.php#L365-L384) and, in turn, [ImageMagick requires Ghostscript to handle PostScript files](http://www.imagemagick.org/script/formats.php). It seems that the base system used by Travis CI does not have Ghostscript installed by default, so it must be explicitly installed for the `connectToThumbnails` API test [to work as expected](https://github.com/nextcloud/gallery/blob/a2671c82233899376752a92cfe0fb45523832039/tests/api/ConnectWithTokenCest.php#L55).
By the way... if someone is bored, [some test images](https://github.com/nextcloud/gallery/commit/718e9be8a54ede8396819ef79ebd61bdba954a01#diff-e5d9 …
=> Fix "connectToThumbnails" API test when run in Travis CI

tests/acceptance/SignInAsUserCept.php
~~Still **Developing** until the test run and confirm that it is fixed ;-)~~ Mmm, the issue that this pull request meant to fix is fixed, so I am changing it to **To review**.
However, there is still one test failing in one of the configurations (it seems that [the login fails when using PHP 7.0 and MySQL](https://travis-ci.org/nextcloud/gallery/jobs/332938158#L1778)). Maybe a timeout? Is it possible to restart a job in Travis CI?
Fixes #375 
The app menu markup has changed in the server. Before, [the image had an `alt` attribute with the name of the app](https://github.com/nextcloud/server/commit/927626cbaaa0da8be0800b6a635783aa3a8ac4ac#diff-8be54a6d336a8809304ef06b951698a9L55), so calling "click" with the app name was enough (as [`click` uses …
=> Fix "SignInAsUser" acceptance test

composer.json, composer.lock
Currently [the master branch of the server requires PHPUnit 6.5](https://github.com/nextcloud/server/pull/8036). The Gallery tests [use the TestCase class from the server](https://github.com/nextcloud/gallery/blob/a2671c82233899376752a92cfe0fb45523832039/tests/_support/Helper/CoreTestCase.php#L26), which in turn [extends the TestCase class from PHPUnit](https://github.com/nextcloud/server/blob/c3424df1f026854ed8adbfdf8d96da7a6562a8dd/tests/lib/TestCase.php#L36), so the PHPUnit version used in the Gallery must match the one used in the server.
Note that [Codeception 2.3.8 is the first version compatible with PHPUnit 6.5](https://github.com/Codeception/Codeception/issues/4715); the required Codeception version is set as `2.3.*` in _composer.json_, so there was no need to modify it (as the …
=> Require PHPUnit 6.5

tests/_support/Page/Acceptance/Login.php, tests/acceptance/SignInAsUserCept.php
It seems that the tests run slower on PHP 7.0 and MySQL in Travis CI (probably due to the use of XDebug); this caused the _Sign in as user_ acceptance test to fail when some actions were executed on an element that had not appeared yet. To fix that now it is checked that the offending elements have appeared in the page before trying to use them.
=> Fix "Sign in as user" acceptance test with PHP 7.0 and MySQL

.travis.yml
Backport of #330 
Fixes https://github.com/nextcloud/gallery/pull/385#issuecomment-361259793
The first two commits of the original pull request are not included in this backport; the first one added the package `dbus-x11`, which was later removed in #333, and the second one upgraded Codeception to 2.3, which was not really needed (and without an update to _composer.lock_ had no effect).
=> [stable12] Make acceptance tests run and pass on Travis CI

tests/api.suite.yml
When run on PHP 7.0 and MySQL in Travis CI sometimes the API tests fail with a timeout; it seems that the tests are slower in that environment, so the timeout has to be increased in that case.
Increasing the timeout simply gives slower tests more time to finish the requests, but it does not affect the other tests in any way, so the timeout was increased for every test.
And with this... we are finally back in green! :-D
=> Fix timeout in API tests

.travis.yml
Backport of #330
Fixes https://github.com/nextcloud/gallery/pull/386#issuecomment-361259941
The first two commits of the original pull request are not included in this backport; the first one added the package dbus-x11, which was later removed in #333, and the second one upgraded Codeception to 2.3, which was not really needed (and without an update to composer.lock had no effect).
=> [stable11] Make acceptance tests run and pass on Travis CI

css/share.css, js/vendor/nextcloud/share.js
Fixes #352 (please see there for screenshots ;-) )
The first three issues were fixed by appending the share drop down to the `#controls` element when shown in the gallery; overriding the CSS rules was not very maintainable as explained in #352, and adding a specific class to inputs and buttons in the actions bar was discarded because those elements belong to the actions bar; it is the share drop down the one that happened to be there, and thus the proper actions bar elements should not be modified just to accommodate "alien" elements.
Note, however, that there are still some slight style differences in the share dropdown when shown in the gallery or in the slideshow (due to the CSS rules for `#controls` descendants), but only minor details and nothing clearly bad like before (for example, …
=> Fix share drop down in gallery not properly shown

css/share.css, js/vendor/nextcloud/share.js
=> [stable13] Fix share drop down in gallery not properly shown

css/share.css
=> Removed old code already present thanks to the files app

css/gallerybutton.css, js/gallerybutton.js
This pull request ensures that the button to switch to the Gallery app is shown in read-only folders.
This is necessary for the fix introduced in nextcloud/server#8589, and it requires nextcloud/server#8588.
=> Fix gallery button hidden in folders without create permission

css/gallerybutton.css, js/gallerybutton.js
=> [stable13] Fix gallery button hidden in folders without create permission

css/public.css, css/styles.css, js/app.js
This pull request addresses [a comment in #350](https://github.com/nextcloud/gallery/issues/350#issuecomment-366921663), although it does not fix the original issue there (the comment is unrelated to the issue, but it has good information ;-) ).
The problem was that the `#controls` element was added outside the `#content-wrapper` element. This caused the controls to overlap the scroll bar of the contents, and also the controls to the right to be hidden when the sidebar of the _JavaScript XMPP Chat_ was open.
Before:
After:
To fix that the `#controls` element was moved inside the `#app` element and the styles were adjusted to keep the same appearance and scrolling behaviour as before.
Note, however, that `#content-wrapper` is kept as the scrolling container; in order to reduce the styles …
=> Fix controls position in gallery layout

css/public.css, css/styles.css, js/app.js
=> [stable13] Fix controls position in gallery layout

js/vendor/nextcloud/share.js
This pull request fixes the _No results found_ tooltip not being shown. It also adds the code needed to hide it based on the one used in the server.
Note, however, that is does not address the problems with that code (for example, if a search is started and while it is being performed the input field is cleared the tooltip would be still shown once the search response is received, even if the input field is now empty).
Probably not worth a backport, although it should be straightforward to do it.
**How to test:**
- Open an album in the Gallery app
- Show the _Share_ dialog for the album
- In the search field type the name of a user that does not exist
**Expected result:**
A _No results found_ tooltip is shown for the input field; if the input field is emptied the tooltip goes away. …
=> Fix "No results found" tooltip

css/share.css
This pull request fixes a regression introduced (by me :-P ) in #404.
The `box-sizing` of `#app` descendants is set to `border-box` in the server. Depending on where it is shown, the _Share with_ input field can be a descendant of `#app` or not, so its icons either use the
`border-box` or the `content-box` sizing depending on the case (`border-box` is used when shown in the main gallery layout, while `content-box` is used when shown in the slideshow layout). Therefore, the padding when using `border-box` sizing has to be set to the content size (`min-width` and `min-height`) plus the padding used in `content-box` sizing.
**Before** (share dialog of an album in gallery layout):
**After** (share dialog of an album in gallery layout):
=> Fix position of icons in "Share with" input field

js/vendor/nextcloud/share.js
After calling `Gallery.Share.share` the UI was restored (the working icon was hidden, the input field enabled...). However, `share` is asynchronous, so the UI was restored while the share was still being
added. Now the UI is restored in the share callbacks, so it is restored once the sharing finished, either successfully or with a failure; in this later case now a notification is also shown.
Probably not worth a backport, although it should be straightforward to do it.
**How to test**
- Modify the code of ShareAPIController and add `sleep(10);` to [the beginning of the `create` method](https://github.com/nextcloud/server/blob/2c073dc53d24c82dd4aaf315327d08463f2c7050/apps/files_sharing/lib/Controller/ShareAPIController.php#L343) to simulate a slow server
- Open an album in the Gallery app …
=> Fix UI while a share is being added

js/vendor/nextcloud/share.js
=> [stable13] Fix "No results found" tooltip

js/vendor/nextcloud/share.js
Follow-up to #415 
If the tooltip is not explicitly hidden it would still be shown once the autocompletion dropdown is shown (behind it while it is open, but fully visible when it is closed).
This unifies its behaviour with the one used in the server, but it does not address its problems (for example, if a search is started and while it is being performed the input field is cleared the tooltip would be still shown once the search response is received, even if the input field is now empty).
**How to test:**
- Open an album in the Gallery app
- Show the Share dialog for the album
- In the search field type the name of a user that exists, and then add any letter to it; the _No results found_ tooltip is shown.
- Remove the extra letter; the autocompletion dropdown is shown
- Click on an empty …
=> Hide "No results found" tooltip on autocompletion

css/share.css, js/vendor/nextcloud/share.js
The Gallery app equivalent of https://github.com/nextcloud/server/pull/7196 cc @nickvergessen @oparoz @MorrisJobke
=> Add confirmation button to share input

css/public.css, css/styles.css, js/breadcrumb.js, js/gallery.js, js/galleryview.js, lib/AppInfo/Application.php, lib/Controller/PageController.php, templates/public.php, tests/unit/Controller/PageControllerTest.php
Use the new PublicPageResponse for NC14+ to render public pages that have the same header actions as the files_sharing app.
Fixes https://github.com/nextcloud/gallery/issues/403 and https://github.com/nextcloud/gallery/issues/358
Requires https://github.com/nextcloud/server/pull/9084
=> Public page response

js/galleryutility.js, js/thumbnail.js, lib/Controller/PreviewController.php, lib/Controller/PreviewPublicController.php
Fixes: #245
Licence: AGPL
Move from EventSources to individual requests for loading thumbnails.
- This would also allow us to fix https://github.com/nextcloud/gallery/issues/14
=> Move from EventSource loading to individual requests

css/styles.css
Sets the gallery app width to 100%.
Closes https://github.com/nextcloud/server/issues/10458
Closes #455
=> Fixes the gallery app width

js/app.js
Fixes: #459 
Like in the filelist app binding the scroll event to $(window) works. This fixes #459 and enables app loading more than the initially loaded images.
Open a folder in gallery with many pictures ( > 100). Try to scroll down and check if all images are loaded.
=> Bind scroll event to window

css/share.css, css/styles.css, js/app.js, js/breadcrumb.js, js/gallery.js, js/galleryview.js, js/slideshow.js, js/slideshowcontrols.js, templates/index.php, templates/public.php
Sorry, have to take a bus, can't explain! :-P
=> Adjust ui to changes in server

lib/Service/ConfigService.php
Requires:
- https://github.com/nextcloud/server/pull/10827
- https://github.com/nextcloud/server/pull/10801
- https://github.com/nextcloud/server/pull/10526
Fixes: https://github.com/owncloud/gallery/issues/737
Licence: AGPL
This is just adding the mime type for apple iPhone HEIC files to the $baseMimeTypes 
* renders HEIC files as thumbnails and in the slideshow
* needs nextcloud 14
- Upload a test image
- Make sure it gets rendered as a thumbnail in gallery
- Make sure it gets rendered in slideshow
- Make sure it can be downloaded from slideshow
@MorrisJobke 
@rullzer 
@oparoz
=> Add HEIC/HEIF support to the gallery

css/share.css
This PR removes the share select height limit which was overwriting the styles from the server in https://github.com/nextcloud/server/pull/11899
=> Remove sharing height limit, since it is overwriting the server defaults

js/slideshowcontrols.js
This will hide the download button for public link shares if the "Hide download" sharing option is set.
Requires https://github.com/nextcloud/server/pull/12531
=> Hide button if download links are hidden for link shares

js/galleryview.js, js/merged.json, js/upload-helper.js, templates/part.content.php
With the new OperationProgressbar the gallery app was not loading properly as the required scripts from the files app were missing.
I'm not to happy with all the files app dependencies in here, but this at least brings the gallery app back to being functional.
=> Quick fix for new files OperationProgressbar

css/share.css
removes the background (which was overlapping the border of the input field) and moves the arrow a little bit up
=> 🐛 FIX: sharing confirm Button

css/gallerybutton.css, templates/part.content.php
Ref: https://github.com/nextcloud/server/issues/16076
>Sort buttons to right and fix layout issues
>Remove "File list" icon in top right
=> Fix gallery sorting buttons and remove filelist ref  #16076

README.md, appinfo/info.xml, lib/Service/ConfigService.php, lib/Service/FilesService.php
Fixes: #438 
Supports blacklisting folders by creating a `.noimage` file.
* `.noimage` functionality
Tested on my system
=> Blacklist using .noimage

js/vendor/nextcloud/share.js
=> Force close all tooltips when closing sharing menu

js/vendor/nextcloud/share.js
Steps to reproduce:
- Go to gallery
- Share a file with a user
- See no results showing up when searching
When trying to share withing the gallery app the autocomplete suggestions were hidden, as they were added to the body and therefore overlayed by the main slideshow which was a z-index of 10000. Appending it to the dropdown makes it use the existing styles for overlaying in https://github.com/nextcloud/gallery/blob/8776be97909c288934b673842fef78c2cd314b32/css/slideshow.css#L190-L193
=> [stable17] Append the autocomplete results to the dropdown container
