nextcloud/gallery

- templates/public.php
Please review @oparoz @LukasReschke @MorrisJobke
> fix share link button label

- templates/public.php
Backport of https://github.com/nextcloud/gallery/pull/6
> [stable10] wording

- templates/public.php
Backport of https://github.com/nextcloud/gallery/pull/6
> [stable9] fix share link button label

- l10n/.tx/config
> update transifex config

- tests/api/CheckTestUsersCest.php
- tests/api/OcsCreateUserCest.php
> [Stable10] Fix OCS requests

- controller/configapicontroller.php
- controller/configcontroller.php
- controller/filesapicontroller.php
- controller/filescontroller.php
- controller/httperror.php
- js/galleryview.js
- tests/unit/controller/ConfigControllerTest.php
- tests/unit/controller/FilesControllerTest.php
- tests/unit/controller/HttpErrorTest.php
@oparoz Please review. I'd also appreciate if you could take care of the required backports. THX.
> Do not display technical error messages

- controller/configapicontroller.php
- controller/configcontroller.php
- controller/filesapicontroller.php
- controller/filescontroller.php
- controller/httperror.php
- tests/unit/GalleryUnitTest.php
- tests/unit/controller/ConfigControllerTest.php
- tests/unit/controller/FilesControllerTest.php
- tests/unit/controller/HttpErrorTest.php
Partial backport of https://github.com/nextcloud/gallery/pull/156
> Stable9 do not leak exception message

- js/galleryview.js
Backport of https://github.com/nextcloud/gallery/pull/155
> Stable9 do set albumpath to empty if error is thrown

- js/galleryview.js
Backport of https://github.com/nextcloud/gallery/pull/155
> Stable10 do set albumpath to empty if error is thrown

- js/vendor/owncloud/share.js
Like for the server as well: https://github.com/nextcloud/server/pull/2132
Please review @oparoz @karlitschek @schiessle
> use Federated Cloud ID wording

- .gitmodules
- .travis.yml
- README.md
- appinfo/info.xml
- build/documentation/docpublisher.sh
- js/vendor/jquery.ui.touch-punch-custom.js
- js/vendor/owncloud/share.js
- templates/part.filenotfounderror.php
- tests/README.MD
- tests/_data/bom-gallery.cnf
- tests/_data/tester-gallery.cnf
- tests/api/GetFilesCest.php
> [Stable10] remove owncloud support

- templates/public.php
> This is NEXTCLOUD

- templates/public.php
> Fix id attribute in title in public template

- .travis.yml
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>
> Add php 7.1 tests

- appinfo/info.xml
Fixes: #214 
Update version for NC 12
> Update to version 17 for NC12

- tests/integration/appinfo/AppTest.php
Fixes: #201 
This fixes the test which broke recently.
> Fix App navigation test

- css/styles.css
- js/breadcrumb.js
Fixes: #138 
1. Click on the "home" button
@jancborchardt
> Breadcrumb fixes

- templates/public.php
Follow up to
https://github.com/nextcloud/server/pull/3868
> Correctly escape the theming footer

- .travis.yml
> Revert "Fix phpunit execution with php7"

- js/galleryview.js
- js/upload-helper.js
> Fix upload after core changes

- tests/acceptance/SignInAsUserCept.php
Lets try to get CI green again!
> Fix the acceptance tests sine we have a fancy new appmenu!

- js/slideshow.js
Calculate the luminance of each picture and adjust the background accordingly.
An image with an average luminance below 60 is considered dark and will get a light background. This is arbitrary.
Does not work on SVG images
@jospoortvliet @jancborchardt
> Initial support for auto-luminance

- css/share.css
Took that dialog out of the past a bit, adjusting background color, border and box-shadow:
After:
Please review @nextcloud/designers @oparoz
> Adjust to Nextcloud style

- css/slideshow.css
- js/slideshowcontrols.js
- templates/slideshow.php
Core css changes were hiding the menu
> fix slideshow menu not being visible

- js/vendor/nextcloud/share.js
Old ocs api doesn't work anymore
> use sharee api to get share targets

- appinfo/app.php
- js/scripts-for-file-app.json
Also need the sharing css and js there.
> fix slideshow sharing from the files app

- css/share.css
- css/slideshow.css
- js/vendor/nextcloud/share.js
- lib/AppInfo/Application.php
- lib/Controller/PageController.php
- tests/unit/Controller/PageControllerTest.php
To test:
Load one of the socialsharing apps and add a call to `$loadScripts()` add the bottom of app.php (yeah not ideal). So at the bottom of https://github.com/nextcloud/socialsharing/blob/master/socialsharing_diaspora/appinfo/app.php#L31-L36
Now open the gallery and click on the share icon.
Todo (need help):
> Add social sharing to share dialog

- js/upload-helper.js
> Update functions to upstream version

- templates/public.php
Backport of #278 to stable12, fixing slideshow
> [stable12] Merge JS for public pages

- js/slideshowcontrols.js
> Fix shared gallery navigation

- lib/Environment/Environment.php
* backport of #288 (see that ticket for the fixed error message)
> [stable12] Fix logged error if file ID is not available

- js/slideshowcontrols.js
> [stable12] Fix shared gallery navigation

- templates/part.internalservererror.php
> Spelling: Nextcloud

- js/galleryview.js
> Spelling: Files

- js/vendor/nextcloud/share.js
* Since we changed some text in the server the translation was no longer
there
* In the server we also removed the link
> Fix the translation source

- js/slideshow.js
- js/vendor/nextcloud/share.js
Needs to be backported to stable12
> Do not use propably outdated core translations

- js/slideshow.js
- js/vendor/nextcloud/share.js
> [stable12] Do not use propably outdated core translations

- js/vendor/nextcloud/share.js
Apparently the Gallery.appName is undefined then.
So just hardcode it.
Fixes #268
> Fix link when opening from files

- templates/public.php
See https://github.com/nextcloud/server/pull/5959
> Logo claim is not used anymore

- js/vendor/nextcloud/share.js
> ![bildschirmfoto vom 2017-08-16 09-21-15](https://user-images.githubusercontent.com/213943/29351750-5cc46298-8264-11e7-9ca2-5562078eb5c4.png)
> Make sure the share-info is visible

- templates/public.php
Backport of #306 
Together with nextcloud/server#6112 it solves #269 for stable12
> [stable12] Fix download icon and logo on gallery share view

- .travis.yml
- lib/Service/FilesService.php
> [stable12] Ignore unavailable storage instead of breaking for all

- css/share.css
- js/gallery.js
- js/slideshowcontrols.js
> [stable12] Fix three dots menu visible in share dropdown

- README.md
See https://github.com/nextcloud/server/pull/7733
> preview_max_scale_factor is not used anymore

- tests/unit/Http/ImageResponseTest.php
See https://github.com/nextcloud/server/pull/7911
> Fix usage of OC_Image

- css/public.css
- css/styles.css
This should fix #364 
I still wasn't able to reproduce it (that's why I didn't notice it in my original PR), but I have a hunch that this is what was causing the issue. Please check if it really fixes it.
> Fixes relative heights for containers

- lib/Service/PreviewService.php
See also #365 
See nextcloud/server#7911
> Fixes usage of OCP\Image

- tests/_support/Page/Acceptance/Login.php
- tests/acceptance/SignInAsUserCept.php
> [stable13] Fix "Sign in as user" acceptance test

- .travis.yml
> [stable13] Fix "connectToThumbnails" API test when run in Travis CI

- .travis.yml
> [stable12] Fix "connectToThumbnails" API test when run in Travis CI

- .travis.yml
> [stable11] Fix "connectToThumbnails" API test when run in Travis CI

- tests/_support/Page/Acceptance/Login.php
- tests/acceptance/SignInAsUserCept.php
Backport of #377 and #379 (ref #384)
> [stable12] Fix "Sign in as user" acceptance test

- tests/api.suite.yml
> [stable13] Fix timeout in API tests

- tests/api.suite.yml
> [stable12] Fix timeout in API tests

- css/share.css
**Backport** : Removed old code already present thanks to the files app #399
> [stable13] Removed old code already present thanks to the files app

- css/share.css
> Fixed sharedwithlist selector

- css/gallerybutton.css
Fix #413
Needs https://github.com/nextcloud/server/pull/8936
@nextcloud/designers
> Fix gallery buttons positionning

- js/vendor/nextcloud/share.js
> [stable13] Fix UI while a share is being added

- css/share.css
> [stable13] Fix position of icons in "Share with" input field

- js/vendor/nextcloud/share.js
> [stable13] Hide "No results found" tooltip on autocompletion

- js/vendor/nextcloud/share.js
Replace the attr function with the data function. 
Fixes #427
> Fix error while clicking on the share link checkbox

- .drone.yml
- js/vendor/nextcloud/share.js
> [stable13]  Fix error while clicking on the share link checkbox
